services:
  # A Docker web service
  - type: web
    name: fastapi-example
    runtime: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r api/requirements.txt
    startCommand: cd api; uvicorn app:app --host 0.0.0.0 --port $PORT
